export const STORE_LAST_TRIP_DATE = 'STORE_LAST_TRIP_DATE';
export const STORE_LAST_TRIP_INFO = 'STORE_LAST_TRIP_INFO';
export const STORE_SELECTED_TRIP_DATE = 'STORE_SELECTED_TRIP_DATE';
export const LOAD_TRIPS = 'LOAD_TRIPS';
export const STORE_TRIPS = 'STORE_TRIPS';
export const STORE_SELECTED_TRIP = 'STORE_SELECTED_TRIP';
export const LOAD_TRIP_JSON = 'LOAD_TRIP_JSON';
export const STORE_TRIP_JSON = 'STORE_TRIP_JSON';
